// ----------------------------------------------------------------
// Foxtrot Engine 2D
// Copyright (C) 2025 JungBae Park. All rights reserved.
//
// Released under the GNU General Public License v3.0
// See LICENSE in root directory for full details.
// ----------------------------------------------------------------

/**
 * @file
 * ResourceManager.cpp
 *
 * The ResourceManager class is responsible for loading, storing,
 * and managing the lifetime of all game assets and resources,
 * such as textures, shaders, materials, sounds, and more.
 *
 * Resources are loaded from .chunk files (containing
 * serialized resources) and stored in hash maps for quick
 * lookup by other engine systems.
 *
 * Note: This file contains platform-specific code for Windows
 * (e.g., Direct3D 11) and is tightly coupled with the Foxtrot
 * engine's rendering and file I/O subsystems.
 */

#include "ResourceManager.h"

#include "ResourceSystem/FTPremade.h"
#include "FTDS/Static/FTString.h"
#include "FileSystem/NullKeys.h"
#include "Plugin/CoreExports.h"

namespace Core
{
	using namespace Common;
	ResourceManager::ResourceManager()
		: mPremades(DBG_NEW ResourcePack<FTPremade>(0))
		, mCSVs(DBG_NEW ResourcePack<FTCSV>(0))
		, mJSONs(DBG_NEW ResourcePack<FTJSON>(0))
		, mTexts(DBG_NEW ResourcePack<FTText>(0))
	{
	}

	ResourceManager::~ResourceManager()
	{
		delete mPremades;
		delete mCSVs;
		delete mJSONs;
		delete mTexts;
	}

	/**
	 * @brief Load resources from a packed data file stream.
	 *
	 * This routine first clears existing resources, loads default (code-generated) ones,
	 * then reads multiple resource data packs from the provided input stream `ifs`.
	 * Each pack is located via Common::FileIOHelper::BeginDataPackLoad and the appropriate loader
	 * template is dispatched (LoadResourceFromChunk or LoadGraphicsResourceFromChunk).
	 *
	 * @param ifs Input file stream positioned at the start of the resource data pack.
	 *
	 * Side-effects:
	 * - Allocates and inserts resource objects into the manager's maps.
	 * - May create GPU resources using the stored mRenderer for graphics resources.
	 *
	 * Notes:
	 * - The function assumes `ifs` is valid and open; file error handling occurs in lower-level helpers.
	 */
	// void ResourceManager::LoadResources(std::ifstream& ifs)
	//{
	//	DeleteAll();
	//
	//	LoadDefaultResources();
	//
	//	std::pair<size_t, Common::FTDS::String> resPack	  = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::RESOURCE_DATA);
	//	size_t							packCount = resPack.first;
	//
	//	std::pair<size_t, Common::FTDS::String> desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTText::FT_TEXT);
	//	LoadResourceFromChunk<FTText>(ifs, mTexts, desc.first);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::CSV::CSV);
	//	LoadResourceFromChunk<FTCSV>(ifs, mCSVs, desc.first);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::JSON::JSON);
	//	LoadResourceFromChunk<FTJSON>(ifs, mJSONs, desc.first);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::Sound::SOUND);
	//	LoadResourceFromChunk<Sound>(ifs, mSounds, desc.first);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTMeshGroup::FT_MESH_GROUP);
	//	LoadGraphicsResourceFromChunk<FTMeshGroup>(ifs, mMeshGroups, desc.first, mRenderer);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTTexture::FT_TEXTURE);
	//	LoadGraphicsResourceFromChunk<FTSprite>(ifs, mSprites, desc.first, mRenderer);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTTileMap::FT_TILEMAP);
	//	LoadResourceFromChunk<FTTileMap>(ifs, mTileMaps, desc.first);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTSpriteAnimation::FT_SPRITE_ANIMATION);
	//	LoadGraphicsResourceFromChunk<FTSpriteAnimation>(ifs, mSpriteAnimations, desc.first, mRenderer);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTSpineAnimation::FT_SPINE_ANIMATION);
	//	LoadGraphicsResourceFromChunk<FTSpineAnimation>(ifs, mSpineAnimations, desc.first, mRenderer);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTFont::FTFONT);
	//	LoadGraphicsResourceFromChunk<FTFont>(ifs, mFonts, desc.first, mRenderer);
	//
	//	desc = Common::FileIOHelper::BeginDataPackLoad(ifs, ChunkKey::FTPremade::FT_PREMADE);
	//	LoadResourceFromChunk<FTPremade>(ifs, mPremades, desc.first);
	//
	//	LoadMaterials();
	// }

	/**
	 * @brief Create and insert minimal default resources generated by code.
	 *
	 * Currently creates a single square mesh (used as a primitive sprite) and inserts
	 * it into the mesh group map under ChunkKey::PRIMITIVE_SQUARE_SPRITE.
	 *
	 * Side-effects:
	 * - Allocates FTMeshData and FTMeshGroup objects.
	 * - Inserts the mesh group into mMeshGroups.
	 */
	void ResourceManager::LoadDefaultResources()
	{
		// Common::FTDS::HashMap<FTVertexShader*>	 VS;
		// Common::FTDS::HashMap<FTGeometryShader*> GS;
		// Common::FTDS::HashMap<FTPixelShader*>	 PS;

		// Common::FTResourceDef resDef{
		//	Common::ChunkKey::NullVal::NULL_OBJECT, Common::ChunkKey::NullVal::NULL_OBJECT
		// };

		/////////////////////////////////
		/////// Vertex Shader Setup /////
		/////////////////////////////////

		// VS.Reserve(5);

		//// 2D sprite animation vertex shader
		// Common::FTDS::String vsPath = Path::Resource::SHADERS_2D;
		// resDef.FileName		= "SpriteVS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// VS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTVertexShader(resDef, mRenderer));

		//// 2D text renderer vertex shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "TextRenderer2DVS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// VS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTVertexShader(resDef, mRenderer));

		//// 2D debug shape vertex shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "DebugShapeVS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// VS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTVertexShader(resDef, mRenderer));

		//// 2D texture vertex shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "TextureVS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// VS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTVertexShader(resDef, mRenderer));

		//// 2D spine animation vertex shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "TextureVSSpine.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// VS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTVertexShader(resDef, mRenderer));

		////////////////////////////////
		/////// Pixel Shader Setup /////
		////////////////////////////////

		// PS.Reserve(6);

		//// 2D sprite animation pixel shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "SpritePS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		//// 2D text renderer pixel shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "TextRenderer2DPS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		//// 2D texture pixel shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "Texture2DPS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		//// 2D spine animation pixel shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "Texture2DSpinePS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		//// 2D debug shape pixel shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "DebugShapePS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		//// 2D texture pixel shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "TexturePS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// PS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTPixelShader(resDef, mRenderer));

		///////////////////////////////////
		/////// Geometry Shader Setup /////
		///////////////////////////////////

		// GS.Reserve(2);

		//// 2D sprite animation geometry shader
		// vsPath			= Path::Resource::SHADERS_2D;
		// resDef.FileName = "SpriteGS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// GS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTGeometryShader(resDef, mRenderer));

		//// 2D debug shape geometry shader
		// vsPath			= Path::Resource::SHADERS;
		// resDef.FileName = "DebugShapeGS.hlsl";
		// vsPath.Append(resDef.FileName);
		// resDef.RelativePath = vsPath.C_Str();

		// GS.Insert(
		//	resDef.FileName,
		//	DBG_NEW FTGeometryShader(resDef, mRenderer));

		////////////////////////////////
		/////// PSO Elements Setup /////
		////////////////////////////////

		// ComPtr<ID3D11BlendState> spriteBS;

		// D3D11_BLEND_DESC blendDesc = {};
		// ZeroMemory(&blendDesc, sizeof(D3D11_BLEND_DESC));
		// blendDesc.AlphaToCoverageEnable	 = FALSE;
		// blendDesc.IndependentBlendEnable = FALSE;

		// D3D11_RENDER_TARGET_BLEND_DESC& rtBlendDesc = blendDesc.RenderTarget[0];
		// rtBlendDesc.BlendEnable						= TRUE;
		// rtBlendDesc.SrcBlend						= D3D11_BLEND_ONE;
		// rtBlendDesc.DestBlend						= D3D11_BLEND_INV_SRC_ALPHA;
		// rtBlendDesc.BlendOp							= D3D11_BLEND_OP_ADD;
		// rtBlendDesc.SrcBlendAlpha					= D3D11_BLEND_ONE;
		// rtBlendDesc.DestBlendAlpha					= D3D11_BLEND_INV_SRC_ALPHA;
		// rtBlendDesc.BlendOpAlpha					= D3D11_BLEND_OP_ADD;
		// rtBlendDesc.RenderTargetWriteMask			= D3D11_COLOR_WRITE_ENABLE_ALL;

		// DX::ThrowIfFailed(mRenderer->GetDevice()->CreateBlendState(&blendDesc, spriteBS.GetAddressOf()));

		// ComPtr<ID3D11DepthStencilState> spriteDSS;

		// D3D11_DEPTH_STENCIL_DESC depthStencilDesc;
		// ZeroMemory(&depthStencilDesc, sizeof(D3D11_DEPTH_STENCIL_DESC));
		// depthStencilDesc.DepthEnable	= false; // false
		// depthStencilDesc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK::D3D11_DEPTH_WRITE_MASK_ALL;
		// depthStencilDesc.DepthFunc		= D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS_EQUAL;

		// DX::ThrowIfFailed(mRenderer->GetDevice()->CreateDepthStencilState(&depthStencilDesc, spriteDSS.GetAddressOf()));

		// mRS->Reserve(2);
		// ComPtr<ID3D11RasterizerState> SolidRS;
		// ComPtr<ID3D11RasterizerState> WireframeRS;

		// D3D11_RASTERIZER_DESC rastDesc;
		// ZeroMemory(&rastDesc, sizeof(D3D11_RASTERIZER_DESC)); // Need this
		//// rastDesc.FillMode = D3D11_FILL_MODE::D3D11_FILL_SOLID;
		// rastDesc.FillMode			   = D3D11_FILL_MODE::D3D11_FILL_SOLID;
		// rastDesc.CullMode			   = D3D11_CULL_MODE::D3D11_CULL_NONE;
		// rastDesc.FrontCounterClockwise = false;
		// rastDesc.DepthClipEnable	   = true;
		// rastDesc.MultisampleEnable	   = true;

		// DX::ThrowIfFailed(mRenderer->GetDevice()->CreateRasterizerState(&rastDesc, SolidRS.GetAddressOf()));

		// rastDesc.FillMode = D3D11_FILL_MODE::D3D11_FILL_WIREFRAME;
		// DX::ThrowIfFailed(mRenderer->GetDevice()->CreateRasterizerState(&rastDesc, WireframeRS.GetAddressOf()));

		// mRS->At(0) = SolidRS;
		// mRS->At(1) = WireframeRS;

		// D3D11_SAMPLER_DESC sampDesc;
		// ZeroMemory(&sampDesc, sizeof(sampDesc));
		// sampDesc.Filter			= D3D11_FILTER_MIN_MAG_MIP_LINEAR;
		// sampDesc.AddressU		= D3D11_TEXTURE_ADDRESS_WRAP;
		// sampDesc.AddressV		= D3D11_TEXTURE_ADDRESS_WRAP;
		// sampDesc.AddressW		= D3D11_TEXTURE_ADDRESS_WRAP;
		// sampDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
		// sampDesc.MinLOD			= 0;
		// sampDesc.MaxLOD			= D3D11_FLOAT32_MAX;

		//// Create the Sample State
		// mDevice->CreateSamplerState(&sampDesc, mSamplerState.GetAddressOf());

		/////////////////////////////
		/////// Assembling PSOs /////
		/////////////////////////////
		// PSODef psoDef;
		//{
		//	psoDef.FileName		= "SpritePSO";
		//	psoDef.RelativePath = Common::ChunkKey::NullVal::NULL_OBJECT;

		//	psoDef.VS			= VS.At("SpriteVS.hlsl")->Value();
		//	psoDef.GS			= GS.At("SpriteGS.hlsl")->Value();
		//	psoDef.PS			= PS.At("SpritePS.hlsl")->Value();
		//	psoDef.BS			= spriteBS;
		//	psoDef.DSS			= spriteDSS;
		//	psoDef.RS			= SolidRS;
		//	psoDef.PrimTopology = D3D11_PRIMITIVE_TOPOLOGY_POINTLIST;

		//	mPSOs->Insert(psoDef.FileName, DBG_NEW D3D11PSO(psoDef));
		//}

		//{
		//	psoDef.FileName		= "SpriteAnimPSO";
		//	psoDef.RelativePath = Common::ChunkKey::NullVal::NULL_OBJECT;

		//	psoDef.VS			= VS.At("SpriteVS.hlsl")->Value();
		//	psoDef.GS			= GS.At("SpriteGS.hlsl")->Value();
		//	psoDef.PS			= PS.At("SpritePS.hlsl")->Value();
		//	psoDef.BS			= spriteBS;
		//	psoDef.DSS			= spriteDSS;
		//	psoDef.RS			= SolidRS;
		//	psoDef.PrimTopology = D3D11_PRIMITIVE_TOPOLOGY_POINTLIST;

		//	mPSOs->Insert(psoDef.FileName, DBG_NEW D3D11PSO(psoDef));
		//}
	}
	Core::FTPremade* ResourceManager::GetPremade(const char* key)
	{
		return mPremades->GetResource(key);
	}

	Core::FTCSV* ResourceManager::GetCSV(const char* key)
	{
		return mCSVs->GetResource(key);
	}

	Core::FTJSON* ResourceManager::GetJSON(const char* key)
	{
		return mJSONs->GetResource(key);
	}

	Core::FTText* ResourceManager::GetText(const char* key)
	{
		return mTexts->GetResource(key);
	}

	FTPremade* GetPremade(const char* key)
	{
		return ResourceManager::GetInstance()->GetPremade(key);
	}
	FTCSV* GetCSV(const char* key)
	{
		return ResourceManager::GetInstance()->GetCSV(key);
	}
	FTJSON* GetJSON(const char* key)
	{
		return ResourceManager::GetInstance()->GetJSON(key);
	}
	FTText* GetText(const char* key)
	{
		return ResourceManager::GetInstance()->GetText(key);
	}
} // namespace Core