#pragma once

#include "FoxtrotEngine/Components/Component.h"
#include "FoxtrotEngine/Components/AIComponent.h"
#include "FoxtrotEngine/Components/AnimatorComponent.h"
#include "FoxtrotEngine/Components/SpriteAnimComponent.h"
#include "FoxtrotEngine/Components/BGSpriteComponent.h"
#include "FoxtrotEngine/Components/ColliderComponent.h"
#include "FoxtrotEngine/Components/InputMoveComponent.h"
#include "FoxtrotEngine/Components/MoveComponent.h"
#include "FoxtrotEngine/Components/Rigidbody2DComponent.h"
#include "FoxtrotEngine/Components/SpriteRendererComponent.h"
#include "FoxtrotEngine/Components/TileMapComponent.h"
#include "FoxtrotEngine/Components/GunFiringComponent.h"
#include "FoxtrotEngine/Components/MeshRendererComponent.h"
#include "FoxtrotEngine/Components/SpineAnimRendererComponent.h"